# Generated by Django 5.0.6 on 2024-06-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book_name', models.CharField(max_length=50)),
                ('book_author', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=500)),
                ('score', models.CharField(max_length=15)),
                ('publisher', models.CharField(max_length=100)),
            ],
        ),
    ]
